spring:
  application:
    name: yoke-ai-agent
  profiles:
    active: local

  # Spring AI MCP 配置
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
        initialize-schema: true

    # MCP 客户端配置
    mcp:
      client:
#        sse:
#          connection:
#            server1:
#              url: http://localhost:8127
        stdio:
          servers-configuration: classpath:mcp-servers.json

    # ollama 配置
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yoke.yokeaiagent.controller
# knife4j 的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
